### ISSUE TITLE
The data widget for Italy seems to have issues with dates after 10/29/2020

### ISSUE THREAD

**Issue by AndreaPi** [epiforecasts/covid#103]
Hi,

first of all, compliments for the very nice project! This is one of the few interactive COVID forecasts for Europe with details at subnational level, which has been serving forecasts continuously since at least April, IIRC.
 Secondly, when I try to look at the cases forecasts, the last date for which the data widget works is 10/29/2020: if I move the cursor to the left, the widget disappears, even though the forecasts (the plots) are there. 

![image](https://user-images.githubusercontent.com/8233615/97639176-5453ba80-1a3e-11eb-9691-4eb0dafd0d87.png)

Could it be an y-scale issue, since 10/29/2020 is precisely the last day on which the forecast CrI still fit inside the plot?

For deaths forecasts, the widget seems to work, even though the reported value of the CrI upper bound doesn't change (it remains fixed at 790), even though the CrI is clearly increasing. Again, this seems to be an issue related to the fact that the CrI upper bound exceeds the y-axis margin.

![image](https://user-images.githubusercontent.com/8233615/97639699-608c4780-1a3f-11eb-84f3-04c8e674d831.png)

**Comment by kathsherratt** [comment]
Hi @AndreaPi - great to hear you have been using the website! Thanks for flagging the issue with plot display. 

While we work on fixing this, I just wanted to link you to the raw [sub-national Italy Rt estimates](https://github.com/epiforecasts/covid-rt-estimates/blob/master/subnational/italy/cases/summary/rt.csv) - in case that's of any use for checking the numbers in the meantime.

Kath

**Comment by AndreaPi** [comment]
Thanks! The numbers seem a wee bit low - an official report by ISS (Istituto Superiore di Sanità) and FBK (Fondazione Bruno Kessler), which I hope will be made publicly available soon (I will link it here if of interest), puts R<sub>t</sub> at 1.7 nationally, and around 2 for Piemonte and Lombardia, using data only up to October the 21st. However, it's to be expected that different methods on different data will yield different values for  R<sub>t</sub>.

**Comment by AndreaPi** [comment]
Hi! Any news on this issue? It hasn't been fixed:

https://epiforecasts.io/covid/posts/national/italy/

**Comment by seabbs** [comment]
Hi Andrea, 

Apologies for not chasing this up. Firstly, we have taken down the interactive plots for the time being as we haven't been able to resource developing the code base behind them. Hopefully, we will be able to resolve that in the near term. 

In terms of the estimates being low this is probably largely driven by two factors. 1. is the assumption used for the generation time/serial interval which may be different and 2. the handling of reported data. We are currently reviewing our generation time assumption (which is detailed in the methods) and in terms of handling of reported data we try and handle known reporting issues (day of the week effects and over dispersion) without resorting to averaging etc. this typically means our estimates are less noisy than those produced from other approaches (this may or may not be a good thing depending on use case and the degree to which the reported data is to be relied on). 

As a follow up question have you explored the data published by the ISS in detail? We currently assume that all data sources may update their numbers over a 3 day period which is why our estimates are always lagged by 4 days (as only at this point do we consider the data final). Do you know if the ISS shows updates over time or if it is static once published? 

Sam

**Comment by AndreaPi** [comment]
Hi Sam,

I've been to a (virtual) conference last week. I'll try to answer your points this weekend.
