### ISSUE TITLE
Washington fail?

### ISSUE THREAD

**Issue by glenviewjeff** [epiforecasts/covid#148]
Something looks very amiss with the Washington predictions. Unless I'm missing something, it looks as if the projection model has failed for some reason. 

https://epiforecasts.io/covid/posts/subnational/united-states/washington/

**Comment by seabbs** [comment]
Thanks for flagging this. It looks like the additional day with no reporting is causing issues? Will keep track of this over the next few days.

**Comment by glenviewjeff** [comment]
There seems to be a flaw in the algorithm; now Texas is going haywire. The data doesn't seem to intuitively justify such an extreme prediction. Looks like this algorithm is simply taking the current growth estimate and assuming it will continue? Seems to me it  might be using too narrow of a period to estimate growth. 

Any idea if the algorithm designers have looked back at the past to see how well predictions performed? An artificial neural network might do the task more reliably, but that's a big project.

**Comment by glenviewjeff** [comment]
Here are a few papers I found doing a fairly quick Google search on how well they did with the networks the researchers tried. I suspect most of these would outperform non ANN methods.

https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0248161
https://ghrp.biomedcentral.com/articles/10.1186/s41256-020-00175-y
https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0243189

**Comment by seabbs** [comment]
Thanks for this (note I am the algorithm designer in this situation) and yes you are correct the underlying assumption is that growth in infections today will continue forward in time. This makes it really only useful for short-term forecasts. I very much agree performance should be checked and we, of course, do that. We also submit this model to the CDC and ECDC forecasting hubs which give a view of how well this model forecasts vs other forecasts. The caveat here is that what we are trying to do is estimate a latent parameter (Rt) that doesn't necessarily improve forecast performance and hence outperforming other models without this limitation is likely not possible. 

The alg in general is a bayesian approximate gaussian process and so fairly in line with current thinking about how to model a time-varying parameter in a robust fashion. The caveat to this is we consider case data alone which limits flexibility and purposely fix growth rate estimates to provide a if today is the future forecast (i.e in effect a scenario). This is an area of active research in the underlying package (https://epiforecasts.io/EpiNow2/) - which is open source and very open to contributions. 

Going to close this issue as both the problems you highlighted appear resolved and were due to changes in the reportinng process for these data streams (missing days etc). This is also something we are exploring as it would be nice if the model was robust to drastic changes in the underlying data sources.

**Comment by glenviewjeff** [comment]
Re-opening because there seem to be ongoing issues like this; algorithm should be more fault tolerant. See Illinois now. Oklahoma looks quite dubious as well.

**Comment by sbfnk** [comment]
I can't see any issue at the moment - if there are ongoing issues please post a screenshot as the links will change daily (and Washington looks entirely sensible to me now). From reading this thread it's not clear what the issue was.

We very much welcome suggestions for improvements to the model, ideally submitted as a Pull Request.
