### ISSUE TITLE
Illinois data error jump

### ISSUE THREAD

**Issue by hartdn** [epiforecasts/covid#153]
Illinois just jumped to 7803 new cases

**Comment by glenviewjeff** [comment]
See #148

**Comment by sbfnk** [comment]
Closing this as Illinois looks fine to me now except some data gaps which we can't take responsibility for.

**Comment by glenviewjeff** [comment]
Actually @sbfnk IDPH does release complete data without holes. They stopped reporting on the weekends, because you know, the pandemic being a thing of the past and all. But they do release the data retrospectively and it's available through their API: https://idph.illinois.gov/DPHPublicInformation/api/COVID/GetIllinoisCases
