### ISSUE TITLE
Projections for New Zealand seem to be erroneous

### ISSUE THREAD

**Issue by MikeGale** [epiforecasts/covid#48]
I note that for a day or two the projections for New Zealand appear to be very high.  The predicted range for the Reproduction number having a range up to 75 and the recorded cases being dwarfed by the predicted range.

I've attached an image to illustrate.

(Niger and Palestine may be similar.)

The doubling time plot also looks odd.

I have not personally checked the number of data points and how that might impact the computations.
![COVID-19_CMMID_NewZealand_TrendsWithDetail_20200430](https://user-images.githubusercontent.com/1784525/80676658-c7d43980-8aa6-11ea-929d-b01132c6e0fc.png)

**Comment by seabbs** [comment]
Hi Mike thanks for opening this. 

This is a known issue for countries/regions with few cases. The low sample size (which is a good thing as it means not many cases) leads to lots of uncertainty in the RT estimate (as the prior has more of an impact) and onset imputation. This uncertainty is then magnified in the forecasts beyond what is plausible.

I think the best step is to not forecasts for places with a low number of cases as we are unlikely to be able to make a reasonable prediction without a much stronger prior on R. I have made this change in the backend but due to the time it takes to compute these forecasts the changes won't show up until tomorrow.

Hopefully, that clarifies the issue. Will continue to monitor this to see if there is a.) a better solution or b.) implemented fix doesn't help.

**Comment by seabbs** [comment]
Updated the master to not forecast regions with very low case counts. Let me know if this doesn't fix.
