### ISSUE TITLE
website update interval

### ISSUE THREAD

**Issue by maia** [epiforecasts/covid#54]
The website was updated every ~2 days for a while, until about a week ago, nothing since. I suggest adding a clear indication on the website with the update frequency/schedule.

**Comment by seabbs** [comment]
Hi @maia, 

Thanks for flagging this. We have been developing an updated approach and dealing with a technical issue. Hopefully, we will be back to daily updates soon. 

If interested in working on a resolution the issue is mapped out here: https://gist.github.com/seabbs/5a9a22950357d569c482535a12645c2c

**Comment by maia** [comment]
Thanks. Unfortunately I'm won't be able to help in identifying the memory leak, but I'm hoping it'll be resolved soon.

**Comment by seabbs** [comment]
Closing as regular updates (1~2 days) will not continue going forward.
