### ISSUE TITLE
Line-list for Colombia

### ISSUE THREAD

**Issue by zmcucunuba** [epiforecasts/covid#72]
Hi - Many thanks for the estimates and projections at subnational level in Colombia. I noticed you mention that line-list data to inform a Colombia specific estimate of the reporting delay was not available. 

Just wanted to point out that the line-list with dates of onset of symptoms (FIS), date of notification, date of diagnosis is made available every day from the official site. I wonder if those can be used to infer delays. 

https://www.ins.gov.co/Noticias/Paginas/Coronavirus.aspx

or a direct link here:
https://www.datos.gov.co/Salud-y-Protecci-n-Social/Casos-positivos-de-COVID-19-en-Colombia/gt2j-8ykr/data

Also, the dataset contains information about health state. Notice that "Asymptomatic" category has increased over time as active searches are increasing, which may led to bias as well.

Thank you!

**Comment by CICATA** [comment]
Hi Dr. Zulma, I am trying to do the same for Mexico. We have the same similar reports released by the Health Secretary(Secretaria de Salud) every day, so we need to make nowcasting to know what is the real situation of COVID in the country. As soon as I have something, I will tell you so we can test with the data of Colombia. Greetings

**Comment by tozanni** [comment]
Hello, 

We have started working in Mexico as well, currently using a shared linelist. However we are in the process of updating to a custom one:

We haven't sent our issues so far, but you can check our results here: 

https://datoscovid.mx/

**Comment by jhellewell14** [comment]
Hello Zulma, I hope you are well! :)

Apologies for the slow reply, we've been trying to sort out techinical problems that have been preventing us from updating the site.

I think the way the site currently works is that everywhere uses the same delay distribution, which is helpful for places where there is no data but makes less sense for places like Colombia like you point out. The approach that we've agreed on is that our site will be as general as possible but that we are keen to make the EpiNow package as user-friendly as possible so that people can re-run the analysis on their own data for countries that they are specifically interested in. Otherwise we'd be spending a lot of time trying to make the analysis for each country unique and we don't have the labour power for that. 

If any of you need any help getting any of the code working on your own data for Colombia or Mexico just comment on here or send me an email at joel.hellewell@lshtm.ac.uk
