### ISSUE TITLE
Refreshing epiforcasts data?

### ISSUE THREAD

**Issue by steviejey** [epiforecasts/covid#87]
Hello.  sorry to bother you guys. I am a journalist and have been following the data that your modelling has produced. I noticed that it had not been updated since the 30th July and wondered if it will be again?

Last week, I did try downloading and installing the scripts to my own system to try and refresh the data but I started to get worried it was going to take up all my PC's space (i think it had downloaded around 25gb of data from git before i stopped it). 

If you are not refreshing this data again, do you have any tips for me to install and run the scripts myself? 

Many thanks for your time, and thanks for creating the scripts, they have been a great inside into what has been happening. - steve

**Comment by seabbs** [comment]
Hi @steviejey, 

Thanks for opening this. We have been developing a new approach and have unfortunately not had the capacity to run both estimates in tandem. The updated estimates can now be found here: https://github.com/epiforecasts/covid-rt-estimates

It should be noted that we are currently just producing estimates for the last 3 months of data (i.e not since the beginning of the pandemic) on a rolling basis. This solves quite a few storage and compute issues but we are looking to also provide estimates across the whole timeseries again.  

Sorry our messaging around this hasn't been very clear - I will leave this open until the website refresh is ready (which hopefully will be soon) and add a note to the README. 

Sam

**Comment by seabbs** [comment]
Closing as site + estimates are now up to date and will be updated regularly going forward.
