### ISSUE TITLE
Why no East Midlands?

### ISSUE THREAD

**Issue by bryand82** [epiforecasts/covid#95]
Why does the published regional data for Covid-19 no longer include anything for the East Midlands?

**Comment by seabbs** [comment]
Thanks for flagging this. 

We have just switched production environments (and teams) and had some initial stability issues. These should now be resolved and estimates from all regions should be updated regularly. 

Closing but feel free to reopen if this crops up again.

**Comment by bryand82** [comment]
I see that data for the East Midlands are missing again.  Please
re-instate this information.
Regards,
Bryan Dawson

**Comment by kathsherratt** [comment]
Hi Bryan,

In the UK, we now estimate and report Rt using counts of cases, admissions, and deaths. Unfortunately the data for admissions only comes in NHS regions, which do not have separate reporting for the East and West Midlands but only as a whole. (Similarly, the North East is now merged with Yorkshire). In order to compare the Rt from each data source, we have also used NHS regions for the Rt based on case and death counts. 

This means we no longer report Rt for the East Midlands and are not planning to re-instate this as a separate region. I hope you are still able to use the Rt for the Midlands, now reported as one region.

Kath

**Comment by seabbs** [comment]
@bryand82 for this sort of scenario (and for many other reasons obviously) we provide all our tools and data under open-source licenses so if access to estimates for the East Midlands is crucial I would suggest exploring restimating. 

Best, 

Sam
